			name: "application-dev"
			on:
			  workflow_dispatch:
			jobs:
			  test:
			    runs-on: ubuntu-latest
			    # ...
			    permissions:
			      id-token: 'write'
			      contents: 'read'
			   
			    steps:
			      - name: GitHub OIDC JWT Token/Conjur Access Token
			        shell: bash
			        run: |
			          JWT_GITHUB_TOKEN=$(curl -H "Authorization:bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "${ACTIONS_ID_TOKEN_REQUEST_URL}?audience=conjur" | jq -r .value)
			          echo "JWT: $JWT_GITHUB_TOKEN" > "jwt-github.txt"
			      # ...
			      - uses: actions/upload-artifact@v4
			        name: Upload JWT File
			        with:
			          name: jwt-github
          path: "jwt-github.txt"
